#dev ya uat profile ko activate karne ke liye:
#--------------------------------------------
spring.profiles.active=dev
#spring.profiles.active=uat

# JWT configuration
#--------------------------------------------
jwt.algorithm.key=amanat@algorithmKey
jwt.issuer=amanat@issuer
jwt.expiryTime=900000
#  15,minutes in milliseconds

# Naming strategy (optional)
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# File upload config
#--------------------------------------------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Static resources (uploads folder)
#--------------------------------------------
spring.web.resources.static-locations=classpath:/static/,file:uploads/

#Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics,mappings
management.endpoint.health.show-details=always

# Eureka Client Configuration
spring.application.name=AMANAT-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#For Creating Super Admin:
#http://localhost:9000/super-admin/create-super-admin
#{
#  "username":"SUPERADMIN",
#  "password":"admin123"
#}